server {
    listen 80 default_server;
    server_name _;
    return 301 http://jellyfin.pirate.lan;
}

# qBittorrent
server {
    listen 80;
    server_name qbittorrent.pirate.lan;
    location / {
        proxy_pass http://qbittorrent:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Radarr
server {
    listen 80;
    server_name radarr.pirate.lan;
    location / {
        proxy_pass http://radarr:7878;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Sonarr
server {
    listen 80;
    server_name sonarr.pirate.lan;
    location / {
        proxy_pass http://sonarr:8989;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Prowlarr
server {
    listen 80;
    server_name prowlarr.pirate.lan;
    location / {
        proxy_pass http://prowlarr:9696;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Bazarr
server {
    listen 80;
    server_name bazarr.pirate.lan;
    location / {
        proxy_pass http://bazarr:6767;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Lidarr
server {
    listen 80;
    server_name lidarr.pirate.lan;
    location / {
        proxy_pass http://lidarr:8686;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Jellyfin
server {
    listen 80;
    server_name jellyfin.pirate.lan;
    location / {
        proxy_pass http://jellyfin:8096;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Jellyseerr
server {
    listen 80;
    server_name jellyseerr.pirate.lan;
    location / {
        proxy_pass http://jellyseerr:5055;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# FlareSolverr
server {
    listen 80;
    server_name flaresolverr.pirate.lan;
    location / {
        proxy_pass http://flaresolverr:8191;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}